name: Deploy to GitHub Pages

on:
  push:
    branches:
      - yampi # O la rama que uses como principal

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Usa la versión recomendada por Vite
      # 2.1 Copiar archivos a public porque tenemos el index con vue incustrado y no se puede hacer build con Vue.
      - name: Copy files to public
        run: |
          mkdir -p public
          cp ./main.js public/ && cp -r ./components public/

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Construir el proyecto
      - name: Build project
        run: npm run build

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
